###Register
POST http://localhost:3001/users/register
Content-Type: application/json

{
  "email": "albert",
  "password": "1222231332"
}

###Login
POST http://localhost:3001/users/login
Content-Type: application/json

{
  "email": "oooooooo",
  "password": "1222222"
}